// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msqdjwwvcnyxptbqijqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcWRqd3d2Y255eHB0YnFpanFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzgxMTIsImV4cCI6MjA1OTY1NDExMn0.v5_4f1rE5Z8di3LhQ16ut2_icq7JS0gcMOmKToO-htU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);